PortfolioProjectNight/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting;
using System.Web;
using System.Web.Mvc;
using PortfolioProjectNight.Models;

namespace PortfolioProjectNight.Controllers
{
    public class DefaultController : Controller
    {
        DbMyPortfolioNightEntities context = new DbMyPortfolioNightEntities();
        public ActionResult Index()
        {
            List<SelectListItem> values = (from x in context.Category.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CategoryName,
                                               Value = x.CategoryID.ToString()

                                           }).ToList();
            ViewBag.value = values;

            return View();
        }
        [HttpPost]
        public ActionResult Index(Contact contact)
        {
            contact.SendDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            contact.IsRead = false;

            context.Contact.Add(contact);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
  
        public PartialViewResult PartialHead()
        {
            return PartialView();

        }
        public PartialViewResult PartialScripts()
        {
            return PartialView();

        }
        public PartialViewResult PartialNavbar()
        {
            return PartialView();

        }
        public PartialViewResult PartialHeader()
        {
            ViewBag.title = context.Profile.Select(x => x.Title).FirstOrDefault();
            ViewBag.description = context.Profile.Select(x => x.Description).FirstOrDefault();
            ViewBag.adress = context.Profile.Select(x => x.Address).FirstOrDefault();
            ViewBag.email = context.Profile.Select(x => x.Email).FirstOrDefault();
            ViewBag.phone = context.Profile.Select(x => x.Phone).FirstOrDefault();
            ViewBag.githup = context.Profile.Select(x => x.Githup).FirstOrDefault();
            ViewBag.imageUrl = context.Profile.Select(x => x.ImageUrl).FirstOrDefault();
            return PartialView();
        }
        public PartialViewResult PartialAbout()
        {
            var values = context.About.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialExperience()
        {
            var values = context.Experience.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialSkill()
        {
            var values = context.Skill.Where(x => x.Status == true).ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialFooter()
        {
            return PartialView();
        }
        public PartialViewResult PartialEducation()
        {
            var values = context.Education.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialTestimonial()
        {
            var values = context.Testimonial.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialContact()
        {
            return PartialView();
        }
        public PartialViewResult PartialPortfolio()
        {
            var values=context.Porfolio.ToList();
            return PartialView(values);
        }
    }
}

PortfolioProjectNight/Views/Default/Index.cshtml
@model PortfolioProjectNight.Models.Contact
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

@Html.Action("PartialHead", "Default")

<body>

    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->
    <!-- Navbar Start -->
    @Html.Action("PartialNavbar", "Default")
    <!-- Navbar End -->
    <!-- Header Start -->
    @Html.Action("PartialHeader", "Default")
    <!-- Header End -->
    <!-- About Start -->
    @Html.Action("PartialAbout", "Default")
    <!-- About End -->
    <!-- Education Start -->
    @Html.Action("PartialEducation", "Default")
    <!-- Education End -->
    <!-- Experience Start -->
    @Html.Action("PartialExperience", "Default")
    <!-- Exparience End -->
    <!-- Skills Start -->
    @Html.Action("PartialSkill", "Default")
    <!-- Skills End -->
    <!-- Service Start -->
    <div class="container-fluid" id="pigraService">
        <div class="container">
            <div class="row g-0">
                <div class="col-lg-3">
                    <div class="service-header h-100 bg-dark pt-6 pe-6 pb-6">
                        <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.1s">
                            <p class="text-white sub-title">My Services</p>
                            <h1 class="display-6 text-white mb-0">What I do for you</h1>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="service-content h-100 pt-6 ps-6 pb-6">
                        <div class="row g-4">
                            <div class="col-12">
                                <div class="service-item p-4 wow fadeInUp" data-wow-delay="0.1s">
                                    <div class="row g-4 align-items-center">
                                        <div class="col-xl-2">
                                            <i class="fas fa-bezier-curve fa-3x"></i>
                                        </div>
                                        <div class="col-xl-3">
                                            <a href="#" class="h4 mb-0">Creative Design</a>
                                        </div>
                                        <div class="col-xl-4">
                                            <p class="mb-0">
                                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis laboriosam repudiandae
                                            </p>
                                        </div>
                                        <div class="col-xl-3">
                                            <p><i class="fa fa-check me-2"></i> UI/UX Design</p>
                                            <p><i class="fa fa-check me-2"></i> Research</p>
                                            <p class="mb-0"><i class="fa fa-check me-2"></i> Mobile App</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="service-item p-4 wow fadeInUp" data-wow-delay="0.3s">
                                    <div class="row g-4 align-items-center">
                                        <div class="col-xl-2">
                                            <i class="fas fa-laptop-code fa-3x"></i>
                                        </div>
                                        <div class="col-xl-3">
                                            <a href="#" class="h4 mb-0">Web Developm</a>
                                        </div>
                                        <div class="col-xl-4">
                                            <p class="mb-0">
                                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis laboriosam repudiandae
                                            </p>
                                        </div>
                                        <div class="col-xl-3">
                                            <p><i class="fa fa-check me-2"></i> UI/UX Design</p>
                                            <p><i class="fa fa-check me-2"></i> Research</p>
                                            <p class="mb-0"><i class="fa fa-check me-2"></i> Mobile App</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="service-item p-4 wow fadeInUp" data-wow-delay="0.5s">
                                    <div class="row g-4 align-items-center">
                                        <div class="col-xl-2">
                                            <i class="fab fa-app-store fa-3x"></i>
                                        </div>
                                        <div class="col-xl-3">
                                            <a href="#" class="h4 mb-0">Mobile Application</a>
                                        </div>
                                        <div class="col-xl-4">
                                            <p class="mb-0">
                                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis laboriosam repudiandae
                                            </p>
                                        </div>
                                        <div class="col-xl-3">
                                            <p><i class="fa fa-check me-2"></i> UI/UX Design</p>
                                            <p><i class="fa fa-check me-2"></i> Research</p>
                                            <p class="mb-0"><i class="fa fa-check me-2"></i> Mobile App</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Service End -->
    <!-- Portfolio Start -->
   @Html.Action("PartialPortfolio","Default")
    <!-- Portfolio End -->
    <!-- Blog Start -->
    <!-- Blog End -->
    <!-- Testimonial Start -->
    @Html.Action("PartialTestimonial", "Default")

    <!-- Testimonial End -->
    <!-- Contact Start -->
    

    <div class="container-fluid" id="pigraContact">
        <div class="container">
            <div class="row g-0">
                @Html.Action("PartialContactSidebar", "Contact")
                <div class="col-lg-9">
                    <div class="contact-content h-100 pt-6 ps-6 pb-6">
                        <div class="bg-light p-4">
                            <div class="row g-5">

                                @Html.Action("PartialContactDetail", "Contact")

                                <div class="col-xl-7 wow fadeInUp" data-wow-delay="0.3s">
                                    <div>
                                        <form method="post">
                                            <div class="row g-3">
                                                <div class="col-lg-12 col-xl-12">
                                                    <div class="form-floating">
                                                        <input type="text" class="form-control border-0" id="name" placeholder="Adınız Soyadınız" name="NameSurname">
                                                        <label for="name">Adınız Soyadınız</label>
                                                    </div>
                                                </div>
                                                <br />
                                                <br />
                                                <div class="col-lg-12 col-xl-12">
                                                    <div class="form-floating">
                                                        <input type="email" class="form-control border-0" id="email" placeholder="Email Adresiniz" name="Email">
                                                        <label for="email">Email Adresiniz</label>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12 ">
                                                    <div class="form-floating">
                                                        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.value, new { @class = "form-control" })
                                                        <label for="text">Konu</label>
                                                    </div>
                                                </div>

                                                <div class="col-12">
                                                    <div class="form-floating">
                                                        <textarea class="form-control border-0" placeholder="Mesajınızı Yazın" name="Message" id="message" style="height: 120px"></textarea>
                                                        <label for="message">Mesajınız</label>
                                                    </div>

                                                </div>
                                                <div class="col-12">
                                                    <button class="btn btn-primary w-100 py-3">Mesajı Gönder</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                @Html.Action("PartialContactLocation", "Contact")
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Contact End -->
    <!-- Footer Start -->
    @Html.Action("PartialFooter", "Default")
    <!-- Footer End -->
    <!-- Back to Top -->
    @Html.Action("PartialScripts", "Default")
</body>

</html>

PortfolioProjectNight/Views/Default/PartialAbout.cshtml
@model List<PortfolioProjectNight.Models.About>

@foreach (var item in Model)
{
<div class="container-fluid" id="pigraAbout">
    <div class="container">
        <div class="row g-0">
            <div class="col-12 col-lg-3">
                <div class="about-header bg-dark h-100 pt-6 pe-6 pb-6">
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.1s">
                        <p class="text-white sub-title">Hakkimda</p>
                        <h1 class="display-6 text-white mb-0">Junior Developer</h1>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-9">
                <div class="about-content h-100 pt-6 ps-6 pb-6">
                    <div class="row g-5">
                        <div class="col-xl-5">
                            <div class="about-img bg-light p-4 wow fadeInUp" data-wow-delay="0.1s">
                                <img src="@item.ImageUrl" class="img-fluid w-100" alt="Image">
                                <div class="sosial-icon">
                                    <a class="btn btn-primary btn-sm-square mb-3" href="#"><i class="fab fa-facebook-f text-white"></i></a>
                                    <a class="btn btn-primary btn-sm-square mb-3" href="#"><i class="fab fa-twitter text-white"></i></a>
                                    <a class="btn btn-primary btn-sm-square mb-3" href="#"><i class="fab fa-instagram text-white"></i></a>
                                    <a class="btn btn-primary btn-sm-square mb-0" href="#"><i class="fab fa-linkedin-in text-white"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-7 wow fadeInUp" data-wow-delay="0.3s">
                            <h4 class="mb-4">@item.Title</h4>
                            <p class="mb-4">
                                @item.Description
                            </p>
                           
                            <a href="#" class="btn btn-primary py-2 px-4"> <i class="fas fa-download me-2"></i>CV mi Indir</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
}

PortfolioProjectNight/Views/Default/PartialEducation.cshtml
@model List<PortfolioProjectNight.Models.Education>
<div class="container-fluid">
    <div class="container">
        <div class="row g-0">
            <div class="col-lg-3">
                <div class="education-header bg-dark h-100 pt-6 pe-6 pb-6">
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.1s">
                        <p class="text-white sub-title">Egitim</p>
                        <h1 class="display-6 text-white mb-0">Egitim Hayatim</h1>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="education-content h-100 pt-6 ps-6 pb-6">
                    <div class="row g-4">

                        @foreach (var item in Model)
                        {
                            <div class="col-12">
                                <div class="education-item rounded p-4 h-100 wow fadeInUp" data-wow-delay="0.1s">
                                    <div class="d-flex align-items-center mb-3">
                                        <p class="fs-5 mb-0 me-4">@item.Title</p>
                                        <div>
                                            <span class="fa fa-calendar me-1"></span> @item.Date
                                        </div>
                                    </div>
                                    <h4 class="mb-3">@item.SubTitle</h4>
                                    <p class="mb-0">
                                        @item.Description
                                    </p>
                                </div>
                            </div>
                        }

                     
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PortfolioProjectNight/Views/Default/PartialExperience.cshtml
@model List<PortfolioProjectNight.Models.Experience>

<div class="container-fluid">
    <div class="container">
        <div class="row g-0">
            <div class="col-lg-3">
                <div class="experience-header bg-dark h-100 pt-6 pe-6 pb-6">
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.1s">
                        <p class="text-white sub-title">Deneyimlerim</p>
                        <h1 class="display-6 text-white mb-0">Calistigim Kurum ve Firmalar</h1>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="experience-content h-100 pt-6 ps-6 pb-6">
                    <div class="row g-4">
                        @foreach (var item in Model)
                        {
                            <div class="col-12">
                                <div class="experience-item rounded p-4 h-100 wow fadeInUp" data-wow-delay="0.1s">
                                    <div class="d-flex align-items-center mb-3">
                                        <p class="fs-5 mb-0 me-4">@item.Title</p>
                                        <div>
                                            <span class="fa fa-calendar me-1"></span> 2017 - 2019
                                        </div>
                                    </div>
                                    <h4 class="mb-3">@item.SubTitle</h4>
                                    <p class="mb-0">
                                        @item.Descriription
                                    </p>
                                </div>
                            </div>
                        }



                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PortfolioProjectNight/Views/Default/PartialFooter.cshtml
<div class="container-fluid footer bg-dark border-bottom-0">
    <div class="container wow fadeIn" data-wow-delay="0.1s">
        <div class="row g-0">
            <div class="col-12">
                <div class="footer-content h-100 pt-6 ps-6 pb-6">
                    <div class="row g-4 align-items-center">
                        <div class="col-12 text-center">
                            <div class="d-flex justify-content-center">
                                <a class="btn btn-light btn-md-square me-3" href=""><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-light btn-md-square me-3" href=""><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-light btn-md-square me-3" href=""><i class="fab fa-instagram"></i></a>
                                <a class="btn btn-light btn-md-square me-0" href=""><i class="fab fa-linkedin-in"></i></a>
                            </div>
                        </div>
                        <div class="col-12 text-center">
                            <span class="text-body"><a href="#" class="border-bottom text-white"><i class="fas fa-copyright text-body me-2"></i>Abdul Hamit KISIR</a>, Tüm haklari saklidir.</span>
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PortfolioProjectNight/Views/Default/PartialHead.cshtml
<head>
    <meta charset="utf-8">
    <title>Abdul Hamit Kisir</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Edu+TAS+Beginner:wght@400..700&family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link rel="stylesheet" href="/Content/Pigra-1.0.0/lib/animate/animate.min.css" />
    <link href="/Content/Pigra-1.0.0/lib/lightbox/css/lightbox.min.css" rel="stylesheet">
    <link href="/Content/Pigra-1.0.0/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="/Content/Pigra-1.0.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/Content/Pigra-1.0.0/css/style.css" rel="stylesheet">
</head>

PortfolioProjectNight/Views/Default/PartialHeader.cshtml
<div class="container-fluid" id="pigraHome">
    <div class="container">
        <div class="row g-0">
            <div class="col-12 col-lg-3">
                <div class="header-content bg-dark h-100 pt-6 pe-6 pb-6">
                    <a href="/Default/Index" class="navbar-brand d-inline-flex pb-5 wow fadeInUp" data-wow-delay="0.1s">
                        <h1 class="display-6 text-white mb-0">Portfolyo</h1>
                    </a>
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.3s">
                        <p class="text-white sub-title">👋 Merhaba Ben Abdul Hamit Kisir </p>
                        <h1 class="display-6 text-white mb-0">Junior Full Stack Devoloper</h1>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-9">
                <div class="header-img d-flex h-100 pt-6 ps-6 pb-6">
                    <div class="row g-5">
                        <div class="col-xl-6 wow fadeInUp" data-wow-delay="0.1s">
                            <div class="bg-light p-4" style="border-radius: 68% 32% 100% 0% / 0% 75% 25% 100%;">
                                <img src="@ViewBag.imageUrl" class="img-fluid w-100" style="border-radius: 68% 32% 100% 0% / 0% 75% 25% 100%;" alt="Image">
                            </div>
                        </div>
                        <div class="col-xl-6 wow fadeInUp" data-wow-delay="0.3s">
                            <h1 class="display-6 mb-4">@ViewBag.title</h1>
                            <p class="mb-4">
                                @ViewBag.description
                            </p>
                            <div class="d-flex align-items-center mb-2">
                                <i class="fas fa-map-marker-alt text-primary me-3"></i>
                                <p class="text-dark mb-0">@ViewBag.adress</p>
                            </div>
                            <div class="d-flex align-items-center mb-2">
                                <i class="fas fa-envelope text-primary me-3"></i>
                                <p class="text-dark mb-0">@ViewBag.email</p>
                            </div>
                            <div class="d-flex align-items-center mb-2">
                                <i class="fa fa-phone-alt text-primary me-3"></i>
                                <p class="text-dark mb-0">@ViewBag.phone</p>
                            </div>
                            <div class="d-flex align-items-center mb-4">
                                <i class="fab fa-firefox-browser text-primary me-3"></i>
                                <p class="text-dark mb-0">@ViewBag.githup</p>
                            </div>                           

                            <div class="d-flex">
                                <a class="btn btn-primary btn-sm-square me-3" href="#"><i class="fab fa-facebook-f text-white"></i></a>
                                <a class="btn btn-primary btn-sm-square me-3" href="#"><i class="fab fa-twitter text-white"></i></a>
                                <a class="btn btn-primary btn-sm-square me-3" href="#"><i class="fab fa-instagram text-white"></i></a>
                                <a class="btn btn-primary btn-sm-square me-0" href="#"><i class="fab fa-linkedin-in text-white"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PortfolioProjectNight/Views/Default/PartialNavbar.cshtml
<div class="container-fluid nav-section border-0">
    <nav class="navbar navbar-light">
        <div class="navbar-nav flex-column">
            <a href="/Default/Index" class="nav-item nav-link active"><span class="fa fa-home"></span> Anasayfa</a>
            <a href="#pigraAbout" class="nav-item nav-link"><span class="far fa-address-card"></span> Hakkimizda</a>
            <a href="#pigraService" class="nav-item nav-link"><span class="fab fa-servicestack"></span> Hizmetler</a>
            <a href="#pigraexperience" class="nav-item nav-link"><span class="fa fa-blog"></span> Yeteneklerim</a>
            <a href="#pigraContact" class="nav-item nav-link"><span class="fas fa-address-book"></span> Bana Yazin</a>
        </div>
    </nav>
</div>

PortfolioProjectNight/Views/Default/PartialPortfolio.cshtml
@model List<PortfolioProjectNight.Models.Porfolio>
<div class="container-fluid">
    <div class="container">
        <div class="row g-0">
            <div class="col-lg-3">
                <div class="portfolio-header h-100 bg-dark pt-6 pe-6 pb-6">
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.1s">
                        <p class="text-white sub-title">Portfolio</p>
                        <h1 class="display-6 text-white mb-0">Son Calismalarim</h1>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="portfolio-content h-100 pt-6 ps-6 pb-6">

                    @foreach (var item in Model)
                    {
                        <div class="portfolio-item py-5 border-bottom wow fadeInUp" data-wow-delay="0.10s">
                            <div class="row g-4 align-items-center">
                                <div class="col-xl-6">
                                    <h4 class="text-body">@item.Title</h4>
                                    <h1 class="display-6 mb-0">@item.Description</h1>
                                </div>
                                <div class="col-9 col-xl-4">
                                    <div class="portfolio-img">
                                        <div class="portfolio-img-inner">
                                            <img src="@item.ImageUrl" class="img-fluid" alt="Image">
                                        </div>
                                    </div>
                                </div>                               
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

PortfolioProjectNight/Views/Default/PartialScripts.cshtml
<a href="#" class="btn btn-primary btn-lg-square back-to-top"><i class="fa fa-arrow-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="/Content/Pigra-1.0.0/lib/wow/wow.min.js"></script>
<script src="/Content/Pigra-1.0.0/lib/easing/easing.min.js"></script>
<script src="/Content/Pigra-1.0.0/lib/waypoints/waypoints.min.js"></script>
<script src="/Content/Pigra-1.0.0/lib/counterup/counterup.min.js"></script>
<script src="/Content/Pigra-1.0.0/lib/lightbox/js/lightbox.min.js"></script>
<script src="/Content/Pigra-1.0.0/lib/owlcarousel/owl.carousel.min.js"></script>


<!-- Template Javascript -->
<script src="/Content/Pigra-1.0.0/js/main.js"></script>